export const navigationData = {
  about: {
    label: '📖 About',
    href: '/about',
    children: [
      { label: 'Our Story', href: '/about/our-story' },
      { label: 'Mission & Philosophy', href: '/about/mission-philosophy' },
      { label: 'Contact', href: '/about/contact' },
    ],
  },
  shop: {
    label: '🛍️ Shop (Marketplace)',
    href: '/shop',
    children: [
      { label: 'Herbal Blends & Teas', href: '/shop/herbal-blends-teas' },
      { label: 'Oils (Essential & Carrier)', href: '/shop/oils' },
      { label: 'Massage & Aromatherapy Kits', href: '/shop/massage-aromatherapy-kits' },
      { label: 'DIY Kits', href: '/shop/diy-kits' },
      { label: 'Digital Products (E-books, PDFs)', href: '/shop/digital-products' },
    ],
  },
  regionAndTraditions: {
    label: '🌍 Region and Traditions',
    href: '/region-and-traditions',
    children: [
      {
        label: '🌎 Global Apothecary',
        href: '/region/global-apothecary',
        children: [
          { label: 'European Folk Herbalism', href: '/region/global-apothecary/european-folk-herbalism' },
          { label: 'Chinese Medicine (TCM)', href: '/region/global-apothecary/tcm' },
          { label: 'Indigenous American', href: '/region/global-apothecary/indigenous-american' },
          { label: 'Middle Eastern Herbalism', href: '/region/global-apothecary/middle-eastern-herbalism' },
        ],
      },
      {
        label: '🌍 African Herbal Apothecary',
        href: '/region/african-apothecary',
        children: [
          {
            label: 'History of African Herbalism',
            href: '/region/african-apothecary/history',
            children: [
              { label: 'Origins and Cultural Lineage', href: '/region/african-apothecary/history/origins' },
              { label: 'Indigenous Medicinal Evolution', href: '/region/african-apothecary/history/evolution' },
            ],
          },
          {
            label: 'African Healing Traditions by Region',
            href: '/region/african-apothecary/traditions',
            children: [
              { label: 'Zulu Healing', href: '/region/african-apothecary/traditions/zulu' },
              { label: 'Xhosa Healing', href: '/region/african-apothecary/traditions/xhosa' },
              { label: 'Tswana & Sotho Healing', href: '/region/african-apothecary/traditions/tswana-sotho' },
              { label: 'Yoruba Healing', href: '/region/african-apothecary/traditions/yoruba' },
              { label: 'Ashanti & Akan Healing', href: '/region/african-apothecary/traditions/ashanti-akan' },
              { label: 'Berber Healing', href: '/region/african-apothecary/traditions/berber' },
              { label: 'Nubian Healing', href: '/region/african-apothecary/traditions/nubian' },
              { label: 'Egyptian Healing', href: '/region/african-apothecary/traditions/egyptian' },
              { label: 'Central & East African Healing', href: '/region/african-apothecary/traditions/central-east-african' },
            ],
          },
          {
            label: 'African Healing Tools & Rituals',
            href: '/region/african-apothecary/tools',
            children: [
              { label: 'Implements, Ceremonial Cleansing, Divination Herbs, Smudge Traditions', href: '/region/african-apothecary/tools/implements' },
              { label: 'Integration of Spirituality, Song, and Medicine', href: '/region/african-apothecary/tools/integration' },
            ],
          },
        ],
      },
    ],
  },
  globalHomeopathyAyurveda: {
    label: '🕉️ Global Homeopathy & Ayurveda',
    href: '/global-homeopathy-ayurveda',
    children: [
      {
        label: 'Homeopathy',
        href: '/global-homeopathy-ayurveda/homeopathy',
        children: [
          { label: 'Principles of Homeopathy', href: '/global-homeopathy-ayurveda/homeopathy/principles' },
          { label: 'Potency & Dilution Scales', href: '/global-homeopathy-ayurveda/homeopathy/potency-dilution' },
          { label: 'Common Homeopathic Remedies', href: '/global-homeopathy-ayurveda/homeopathy/remedies' },
          { label: 'African-Adapted Homeopathic Approaches', href: '/global-homeopathy-ayurveda/homeopathy/african-adapted' },
        ],
      },
      {
        label: 'Ayurveda',
        href: '/global-homeopathy-ayurveda/ayurveda',
        children: [
          { label: 'The Three Doshas: Vata, Pitta, Kapha', href: '/global-homeopathy-ayurveda/ayurveda/doshas' },
          { label: 'Ayurvedic Herbs & Spices', href: '/global-homeopathy-ayurveda/ayurveda/herbs-spices' },
          { label: 'Herbal Formulations by Dosha', href: '/global-homeopathy-ayurveda/ayurveda/formulations' },
          { label: 'Ayurvedic Oils & Body Treatments', href: '/global-homeopathy-ayurveda/ayurveda/oils-treatments' },
          { label: 'Ayurvedic Massage (Abhyanga & Marma Therapy)', href: '/global-homeopathy-ayurveda/ayurveda/massage' },
        ],
      },
    ],
  },
  naturalIngredientsOils: {
    label: '🌿 Natural Ingredients & Oils',
    href: '/natural-ingredients-oils',
    children: [
      {
        label: 'Plant Parts',
        href: '/natural-ingredients-oils/plant-parts',
        children: [
          { label: 'Seeds', href: '/natural-ingredients-oils/plant-parts/seeds' },
          { label: 'Roots', href: '/natural-ingredients-oils/plant-parts/roots' },
          { label: 'Bark', href: '/natural-ingredients-oils/plant-parts/bark' },
          { label: 'Leaves', href: '/natural-ingredients-oils/plant-parts/leaves' },
          { label: 'Flowers', href: '/natural-ingredients-oils/plant-parts/flowers' },
          { label: 'Fruit', href: '/natural-ingredients-oils/plant-parts/fruit' },
          { label: 'Resin & Sap', href: '/natural-ingredients-oils/plant-parts/resin-sap' },
        ],
      },
      {
        label: 'Carrier Oils',
        href: '/natural-ingredients-oils/carrier-oils',
        children: [
          { label: 'Sweet Almond Oil', href: '/natural-ingredients-oils/carrier-oils/sweet-almond' },
          { label: 'Jojoba Oil', href: '/natural-ingredients-oils/carrier-oils/jojoba' },
          { label: 'Coconut Oil', href: '/natural-ingredients-oils/carrier-oils/coconut' },
          { label: 'Grapeseed Oil', href: '/natural-ingredients-oils/carrier-oils/grapeseed' },
          { label: 'Argan Oil', href: '/natural-ingredients-oils/carrier-oils/argan' },
          { label: 'Castor Oil', href: '/natural-ingredients-oils/carrier-oils/castor' },
          { label: 'Avocado Oil', href: '/natural-ingredients-oils/carrier-oils/avocado' },
          { label: 'Rosehip Seed Oil', href: '/natural-ingredients-oils/carrier-oils/rosehip-seed' },
          { label: 'Hemp Seed Oil', href: '/natural-ingredients-oils/carrier-oils/hemp-seed' },
          { label: 'Black Seed Oil', href: '/natural-ingredients-oils/carrier-oils/black-seed' },
          { label: 'Tamanu Oil', href: '/natural-ingredients-oils/carrier-oils/tamanu' },
        ],
      },
      {
        label: 'Essential Oils',
        href: '/natural-ingredients-oils/essential-oils',
        children: [
          { label: 'Lavender', href: '/natural-ingredients-oils/essential-oils/lavender' },
          { label: 'Chamomile (Roman/German)', href: '/natural-ingredients-oils/essential-oils/chamomile' },
          { label: 'Rose', href: '/natural-ingredients-oils/essential-oils/rose' },
          { label: 'Jasmine', href: '/natural-ingredients-oils/essential-oils/jasmine' },
          { label: 'Ylang Ylang', href: '/natural-ingredients-oils/essential-oils/ylang-ylang' },
          { label: 'Geranium', href: '/natural-ingredients-oils/essential-oils/geranium' },
          { label: 'Eucalyptus', href: '/natural-ingredients-oils/essential-oils/eucalyptus' },
          { label: 'Peppermint', href: '/natural-ingredients-oils/essential-oils/peppermint' },
          { label: 'Tea Tree', href: '/natural-ingredients-oils/essential-oils/tea-tree' },
          { label: 'Rosemary', href: '/natural-ingredients-oils/essential-oils/rosemary' },
          { label: 'Patchouli', href: '/natural-ingredients-oils/essential-oils/patchouli' },
          { label: 'Frankincense', href: '/natural-ingredients-oils/essential-oils/frankincense' },
          { label: 'Myrrh', href: '/natural-ingredients-oils/essential-oils/myrrh' },
          { label: 'Sandalwood', href: '/natural-ingredients-oils/essential-oils/sandalwood' },
          { label: 'Lemon', href: '/natural-ingredients-oils/essential-oils/lemon' },
          { label: 'Orange (Sweet)', href: '/natural-ingredients-oils/essential-oils/orange' },
          { label: 'Bergamot', href: '/natural-ingredients-oils/essential-oils/bergamot' },
        ],
      },
    ],
  },
  aromatherapyMassage: {
    label: '🌸 Aromatherapy & Massage Therapy',
    href: '/aromatherapy-massage',
    children: [
      {
        label: 'Aromatherapy',
        href: '/aromatherapy-massage/aromatherapy',
        children: [
          { label: 'Principles of Aromatherapy', href: '/aromatherapy-massage/aromatherapy/principles' },
          { label: 'Essential Oil Blending Guide', href: '/aromatherapy-massage/aromatherapy/blending-guide' },
          { label: 'Diffusion & Inhalation Methods', href: '/aromatherapy-massage/aromatherapy/diffusion-inhalation' },
          { label: 'Emotional & Energetic Healing', href: '/aromatherapy-massage/aromatherapy/emotional-healing' },
          { label: 'Chakra & Mood Blends', href: '/aromatherapy-massage/aromatherapy/chakra-mood-blends' },
          { label: 'Safety, Dilution & Contraindications', href: '/aromatherapy-massage/aromatherapy/safety' },
        ],
      },
      {
        label: 'Massage Therapy',
        href: '/aromatherapy-massage/massage-therapy',
        children: [
          { label: 'Introduction to Therapeutic Massage', href: '/aromatherapy-massage/massage-therapy/introduction' },
          {
            label: 'Massage Techniques',
            href: '/aromatherapy-massage/massage-therapy/techniques',
            children: [
              { label: 'Swedish Massage', href: '/aromatherapy-massage/massage-therapy/techniques/swedish' },
              { label: 'Deep Tissue', href: '/aromatherapy-massage/massage-therapy/techniques/deep-tissue' },
              { label: 'Lymphatic Drainage', href: '/aromatherapy-massage/massage-therapy/techniques/lymphatic-drainage' },
              { label: 'Aromatherapy Massage', href: '/aromatherapy-massage/massage-therapy/techniques/aromatherapy' },
              { label: 'Ayurvedic Massage (Abhyanga)', href: '/aromatherapy-massage/massage-therapy/techniques/ayurvedic' },
            ],
          },
          { label: 'Massage Oil Recipes', href: '/aromatherapy-massage/massage-therapy/recipes' },
          { label: 'Carrier & Essential Oil Synergies', href: '/aromatherapy-massage/massage-therapy/synergies' },
          { label: 'Body-Mind Healing & Relaxation', href: '/aromatherapy-massage/massage-therapy/body-mind-healing' },
        ],
      },
    ],
  },
  benefits: {
    label: '💚 Benefits',
    href: '/benefits',
    children: [
      {
        label: 'Physical',
        href: '/benefits/physical',
        children: [
          { label: 'Sleep Aid', href: '/benefits/physical/sleep-aid' },
          { label: 'Energy & Vitality', href: '/benefits/physical/energy-vitality' },
          { label: 'Weight Management', href: '/benefits/physical/weight-management' },
          { label: 'Digestive & Gut Health', href: '/benefits/physical/digestive-gut-health' },
          { label: 'Detox & Liver Health', href: '/benefits/physical/detox-liver-health' },
          { label: 'Immunity Boost', href: '/benefits/physical/immunity-boost' },
          {
            label: 'Skin Health',
            href: '/benefits/physical/skin-health',
            children: [
              { label: 'Dark Mark Removal', href: '/benefits/physical/skin-health/dark-mark-removal' },
              { label: 'Anti-Aging', href: '/benefits/physical/skin-health/anti-aging' },
              { label: '💧 Hydration & Nourishment', href: '/benefits/physical/skin-health/hydration-nourishment' },
              { label: '🔥 Anti-Inflammatory & Soothing', href: '/benefits/physical/skin-health/anti-inflammatory-soothing' },
              { label: '✨ Brightening & Anti-Aging', href: '/benefits/physical/skin-health/brightening-anti-aging' },
              { label: '🧴 Cleansing, Astringent & Toning', href: '/benefits/physical/skin-health/cleansing-astringent-toning' },
              { label: '💆‍♀️ Calming, Soothing & Aromatherapy', href: '/benefits/physical/skin-health/calming-soothing-aromatherapy' },
              { label: '🦠 Antibacterial & Acne Support', href: '/benefits/physical/skin-health/antibacterial-acne-support' },
            ],
          },
          { label: 'Hair Growth & Scalp Health', href: '/benefits/physical/hair-growth-scalp-health' },
          { label: 'Pain Relief & Anti-Inflammatory', href: '/benefits/physical/pain-relief-anti-inflammatory' },
          { label: 'Antimicrobial & Antiviral', href: '/benefits/physical/antimicrobial-antiviral' },
          { label: 'Hormonal & Menstrual Health', href: '/benefits/physical/hormonal-menstrual-health' },
          { label: 'Circulation & Cardiovascular', href: '/benefits/physical/circulation-cardiovascular' },
          { label: 'Aphrodisiac / Libido Support', href: '/benefits/physical/aphrodisiac-libido-support' },
          { label: 'Arousal & Performance', href: '/benefits/physical/arousal-performance' },
        ],
      },
      {
        label: 'Emotional & Mental Health',
        href: '/benefits/emotional-mental-health',
        children: [
          { label: 'Stress Relief & Anxiety', href: '/benefits/emotional-mental-health/stress-relief-anxiety' },
          { label: 'Focus & Memory', href: '/benefits/emotional-mental-health/focus-memory' },
          { label: 'Emotional Balance', href: '/benefits/emotional-mental-health/emotional-balance' },
          { label: 'Spiritual Grounding & Cleansing', href: '/benefits/emotional-mental-health/spiritual-grounding-cleansing' },
        ],
      },
    ],
  },
  diyRecipes: {
    label: '🧪 DIY & Recipes',
    href: '/diy-recipes',
    children: [
      { label: 'Homeopathy & Apothecary', href: '/diy-recipes/homeopathy-apothecary' },
      { label: 'African Remedies', href: '/diy-recipes/african-remedies' },
      { label: 'Global Remedies', href: '/diy-recipes/global-remedies' },
      { label: 'Teas & Tonics', href: '/diy-recipes/teas-tonics' },
      { label: 'Tinctures & Extracts', href: '/diy-recipes/tinctures-extracts' },
      { label: 'Balms & Salves', href: '/diy-recipes/balms-salves' },
      { label: 'Skin & Hair Recipes', href: '/diy-recipes/skin-hair-recipes' },
      { label: 'Massage Oils & Body Blends', href: '/diy-recipes/massage-oils-body-blends' },
      { label: 'Aromatherapy Blends', href: '/diy-recipes/aromatherapy-blends' },
    ],
  },
  educationHub: {
    label: '📚 Education Hub',
    href: '/education-hub',
    children: [
      { label: 'Safety & Dosage', href: '/education-hub/safety-dosage' },
      { label: 'Mixing Charts (Oils & Blends)', href: '/education-hub/mixing-charts' },
      { label: 'DIY Apothecary Tutorials', href: '/education-hub/diy-apothecary-tutorials' },
      { label: 'Aromatherapy & Massage Certification Guides', href: '/education-hub/aromatherapy-massage-certification' },
      { label: 'Homeopathic Basics', href: '/education-hub/homeopathic-basics' },
      { label: 'Ayurvedic Principles', href: '/education-hub/ayurvedic-principles' },
    ],
  },
  nutritionWellness: {
    label: '🍃 Nutrition & Wellness',
    href: '/nutrition-wellness',
    children: [
      { label: 'Herbal Nutrition', href: '/nutrition- wellness/herbal-nutrition' },
      { label: 'Gut Health & Probiotics', href: '/nutrition-wellness/gut-health-probiotics' },
      { label: 'Detox & Cleansing', href: '/nutrition-wellness/detox-cleansing' },
      { label: 'Herbal Weight Management', href: '/nutrition-wellness/herbal-weight-management' },
    ],
  },
  mindSpirit: {
    label: '🕊️ Mind & Spirit',
    href: '/mind-spirit',
    children: [
      { label: 'Relaxation & Sleep', href: '/mind-spirit/relaxation-sleep' },
      { label: 'Mood & Anxiety', href: '/mind-spirit/mood-anxiety' },
      { label: 'Focus & Memory', href: 'mind-spirit/focus-memory' },
      { label: 'Spiritual Cleansing', href: '/mind-spirit/spiritual-cleansing' },
      { label: 'Energy & Chakra Balancing', href: '/mind-spirit/energy-chakra-balancing' },
    ],
  },
  communityLearning: {
    label: '🌐 Community & Learning',
    href: '/community-learning',
    children: [
      { label: 'Forum / User Contributions', href: '/community-learning/forum' },
      { label: 'Videos & Tutorials', href: '/community-learning/videos-tutorials' },
      { label: 'Events & Workshops', href: '/community-learning/events-workshop' },
    ],
  },
};
